// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package repository

import (
	"context"
)

const getinternalUsers = `-- name: GetinternalUsers :many
select id, name, email, password, role, is_active, is_deleted, created_at, updated_at, deleted_at from public."internal_user"
`

func (q *Queries) GetinternalUsers(ctx context.Context) ([]InternalUser, error) {
	rows, err := q.db.Query(ctx, getinternalUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InternalUser
	for rows.Next() {
		var i InternalUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.IsActive,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
